# Configuración del Servidor
spring.application.name=ms-verificador-adapter
server.port=8082

# URL del servicio Ticket Authority
ticket.authority.url=http://localhost:8081

# Logging
logging.level.com.congresos=DEBUG
logging.level.org.springframework.web=DEBUG
