# Configuración del Servidor
spring.application.name=ms-ticket-authority
server.port=8081

# Clave secreta para firmar tickets
ticket.signature.secret=CLAVE_SECRETA_PARA_FIRMAR_TICKETS_QR_MUY_SEGURA_2025

# Logging
logging.level.com.congresos=DEBUG
logging.level.org.springframework.web=DEBUG
